# Generated by Django 5.0 on 2023-12-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='unitPrice',
        ),
    ]
