# Generated by Django 5.0 on 2023-12-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_rename_price_book_unitprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book_images/default.jpg', upload_to='book_images/'),
        ),
    ]
